name: AWS 
on:
  workflow_dispatch:

jobs:
  manually:    
    name: manually
    runs-on: ubuntu-latest
    steps:      
    - name: test
      run: |
        curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x copilot && sudo mv copilot /usr/local/bin/copilot && copilot --help

  action:    
    name: action
    runs-on: ubuntu-latest
    steps:      
    - uses: ksivamuthu/aws-copilot-github-action@v0.0.8
      with:
        command: install
